Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/chkngo/urls.py
from django.contrib import admin
from django.urls import path
from webapp import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from webapp.views import (searchposts)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LandingPage, name = "LandingPage"),
    path('restaurants/', views.RestoList, name = "RestoList"),
    path('restaurants/<RestoID>/', views.RestoView, name = "RestoView"),
    path('restaurants/<RestoID>/manage',views.RestaurantManagement, name = 'RestoManage'),
    path('restaurants/<RestoID>/ReviewUpload/', views.ReviewUpload, name = 'ReviewUpload'),
    # path('restaurants/<RestoID>/SeeWaitList/', views.SeeWaitlist, name = 'SeeWaitList'),
    path('restaurants/<RestoID>/DeleteEntry/<first_name>/<last_name>/<id>/', views.DeleteEntry, name ="DeleteEntry"),
    path('restaurants/<RestoID>/SeatEntry/<id>', views.SeatEntry, name = "SeatEntry"),
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html'), name = 'Login'),
    # path('login/', views.Login, name = "Login"),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'logout.html'),name = 'Logout'),
    path('register/', views.Register, name = 'Register'),
    path('register/make_category', views.MakeCategory, name = "MakeCategory"),
	path('search/', views.searchposts, name="Search"),
	url(r'^search/', include(('webapp.urls',"Search"), namespace='search')),

]

if settings.DEBUG:
    urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (searchposts)

urlpatterns = [
     url(r'^$', searchposts, name='searchposts'),

]

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class ReviewForm(forms.ModelForm):
    Rating = forms.IntegerField(max_value=5, min_value= 0)
    ReviewDetail = forms.CharField(max_length = 250, label = 'Review')
    class Meta:
        model = Review
        fields = ['Rating','ReviewDetail']

class RegistrationForm(UserCreationForm):
    CUSTOMER = "CU"
    RESTAURANT_MANAGER = "RM"
    USER_TYPES = [
        (CUSTOMER,'Customer'),
        (RESTAURANT_MANAGER,'Restaurant Manager'),
    ]
    user_type = forms.ChoiceField(choices = USER_TYPES)
    email = forms.EmailField(required = True)
    first_name = forms.CharField(required = True)
    last_name = forms.CharField(required = True)
    contact = forms.CharField(required=False, max_length=11, min_length= 3)
    class Meta :
        model = CustomUser
        fields = [
            'first_name',
            'last_name',
            'user_type',
            'username',
            'email',
            'contact',
            'password1',
            'password2'
            ]

class RMRegistrationForm(forms.ModelForm):
    INPUT_FORMATS = ['%H:%M',]
    RestoID = forms.CharField(max_length= 30, required = False, label = "Restaurant ID")
    Category = forms.ModelMultipleChoiceField(queryset = Categories.objects.all(), required = False)
    Open_time = forms.TimeField(input_formats= INPUT_FORMATS, label= "Opening Time", required = False )
    Closing_time = forms.TimeField(input_formats= INPUT_FORMATS, label= "Closing Time",required = False )
    
    class Meta:
        model = Restaurant
        fields= ['RestoID','Open_time','Closing_time','Address','Landline','Contact','Category']


class CategoryForm(forms.ModelForm):
    CatName = forms.CharField(max_length = 30, label = 'Category Name')
    class Meta:
        model = Categories
        fields = ['CatName']

class RestoEditForm(forms.ModelForm):
    INPUT_FORMATS = ['%H:%M',]
    Open_time = forms.TimeField(input_formats= INPUT_FORMATS, label= "Opening Time", required = False )
    Closing_time = forms.TimeField(input_formats= INPUT_FORMATS, label= "Closing Time", required = False )
    Address = forms.CharField(required = False, max_length= 100)
    Landline = forms.CharField(required = False, max_length=10)
    Contact = forms.CharField(required = False, max_length=11)
    
    class Meta:
        model = Restaurant
        fields = ['Open_time','Closing_time','Address','Landline','Contact']

class WaitListEntryForm(forms.ModelForm):
    first_name = forms.CharField(max_length= 30, label = "First Name")
    last_name = forms.CharField(max_length= 30, label = "Last Name")
    PaxCount = forms.IntegerField(min_value=1, label = "Party Size")
    class Meta:
        model = WaitListEntry
        fields = ['first_name', 'last_name', 'PaxCount']

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.contrib import messages
import uuid
import datetime,statistics
from django.db.models import Q
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
#A simple mean Average Algorithm, input must be a list of a certain element, outputs integer mean
def average(list):
    AveNum = 0
    AveCount = 0
    for x in list:
        AveNum += x.Rating
        AveCount += 1
    AveNum = AveNum / AveCount
    return AveNum

#Mode Algorithm given queryset of waitlistentries





# Mode average function using statistics
def mode(list):
    try:
        return statistics.mode(list)
    except:
        return statistics.mean(list)


# Create your views here.
# def Home(request):
# def SeeWaitlist(request, RestoID):
#     if request.method == 'POST':
#         form = WaitListEntryForm(request.POST)
#         if form.is_valid():
#             temp_WLE= WaitListEntry(RestoID = Restaurant.objects.get(RestoID = RestoID),
#                                     first_name = form.cleaned_data.get('first_name'),
#                                     last_name = form.cleaned_data.get('last_name'),
#                                     PaxCount = form.cleaned_data.get('PaxCount'))
#             temp_WLE.save()
#             return redirect('RestoView', RestoID = RestoID)
#     else:
#         form = WaitListEntryForm()
#     context = {'form': form}
#     return render(request,'wait_list.html',context)
def logout_view(request):
    logout(request)
    return redirect('LandingPage')

def LandingPage(request):
    if request.user.user_type == "CU":
        category_list = Categories.objects.values('CatName')
        context = {'category_list': category_list}
        return render(request, 'landingPage.html', context)
    elif request.user.user_type == "RM":
        RestoToView = Restaurant.objects.get(MngID = request.user)
        return redirect('RestoView', RestoID = RestoToView.RestoID)

def RestoList(request):
    resto_list = Restaurant.objects.all()
    # context = {'resto_list': resto_list}
    return render(request, 'resto_list.html')

def RestoView(request, RestoID):
    resto_deets = Restaurant.objects.get(RestoID = RestoID)
    WaitList = WaitListEntry.objects.filter(RestoID = RestoID,
                                            Seated = False
                                            )
    if request.method == 'POST':
        form = WaitListEntryForm(request.POST)
        if form.is_valid():
            temp_WLE= WaitListEntry(RestoID = Restaurant.objects.get(RestoID = RestoID),
                                    first_name = form.cleaned_data.get('first_name'),
                                    last_name = form.cleaned_data.get('last_name'),
                                    PaxCount = form.cleaned_data.get('PaxCount'))
            temp_WLE.save()
            return redirect('RestoView', RestoID = RestoID)
    else:
        form = WaitListEntryForm()
    # context = {}
    context = {'resto_deets': resto_deets, 'WaitList':WaitList, 'user':request.user,'form': form}
    return render(request, 'restoView.html', context)

def ReviewUpload(request, RestoID):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            ReviewObj = Review()
            ReviewObj.ReviewID = uuid.uuid1()
            ReviewObj.RestoID = Restaurant.objects.get(RestoID = RestoID)
            ReviewObj.Rating = form.cleaned_data.get('Rating')
            ReviewObj.save()
            #Update Restaurant Review Average
            Resto = Restaurant.objects.get(RestoID = RestoID)
            AllRatings = Review.objects.filter(RestoID = RestoID)
            AveRate = average(AllRatings)
            Resto.Rating = AveRate
            Resto.save(force_update = True)
        return redirect('RestoView', RestoID = RestoID)
    else:
        form = ReviewForm()
        context= {'form':form}
        return render (request, 'review_upload.html', context)

# def Login(request):
#     if request.method == "POST":
#         form = AuthenticationForm(data = request.POST)
#         if (form.is_valid):
#             # log in the user
#             return redirect('LandingPage')
#     else:
#         form = AuthenticationForm()
#     return render(request,'login.html', {'form':form})

def Register(request):
    if request.method =="POST":
        form = RegistrationForm(request.POST)
        form2 = RMRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            temp_user = CustomUser.objects.get(username = username)
            print(form.cleaned_data.get('user_type'))
            if form.cleaned_data.get('user_type') == 'RM':
                if form2.is_valid():
                    opTime = form2.cleaned_data.get('Open_time')
                    clTime = form2.cleaned_data.get('Closing_time')
                    Add = form2.cleaned_data.get('Address')
                    Land = form2.cleaned_data.get('Landline')
                    Cont = form2.cleaned_data.get('Contact')
                    Cats = form2.cleaned_data.get('Category')
                    temp_Res = Restaurant(RestoID = form2.cleaned_data.get('RestoID'),
                                        MngID = temp_user,
                                        Open_time = opTime,
                                        Closing_time = clTime,
                                        Address = Add,
                                        Landline = Land,
                                        Contact = Cont
                                        )
                    print(temp_Res)
                    temp_Res.save()
                    for ii in Cats:
                        temp_Res.Category.add(ii)
                    print(Restaurant.objects.all())
            messages.success(request,f'Account Created for {username}! go ahead and log in!')
            return redirect('Register')
    else:
        form = RegistrationForm()
        form2 = RMRegistrationForm()
    context = {'form':form,'form2':form2}
    return render(request,'registration_page.html',context)

def MakeCategory(request):
    if(request.method == "POST"):
        form = CategoryForm(request.POST)
        if form.is_valid():
            tempCat = Categories()
            tempCat.CatID = uuid.uuid1()
            tempCat.CatName = form.cleaned_data.get('CatName')
            tempCat.save()
            return redirect('Register')
    else:
        form = CategoryForm()
    context = {'form':form}
    return render(request,'make_category.html',context)

def RestaurantManagement(request,RestoID):
    if not request.user.user_type == "RM" or (request.user.is_authenticated and not Restaurant.objects.get(RestoID = RestoID).MngID == request.user):
        messages.success(request,'page you\'re tryring to access is forbidden')
        return redirect('RestoList')
    elif request.method == 'POST':
        form = RestoEditForm(data = request.POST)
        temp_resto = Restaurant.objects.get(RestoID = RestoID)
        if form.is_valid():
            if form.cleaned_data.get('Open_time') == None:
                print("Nothing change Open_time")
            else:
                temp_resto.Open_time = form.cleaned_data.get('Open_time')
            if form.cleaned_data.get('Closing_time') == None:
                print("Nothing change Closing_time")
            else:
                temp_resto.Closing_time = form.cleaned_data.get('Closing_time')
            if form.cleaned_data.get('Address') == '':
                print("Nothing change Address")
            else:
                temp_resto.Address = form.cleaned_data.get('Address')
            if form.cleaned_data.get('Landline') == '':
                print("Nothing change Landline")
            else:
                temp_resto.Landline = form.cleaned_data.get('Landline')
            if form.cleaned_data.get('Contact') == '':
                print("Nothing change Contact")
            else:
                temp_resto.Contact = form.cleaned_data.get('Contact')
            temp_resto.save(force_update = True)
            return redirect('RestoView', RestoID = RestoID)
    else:
        form = RestoEditForm()
    context = {'form':form}
    return render(request, 'restaurant_management.html',context)

def DeleteEntry(request,RestoID,first_name,last_name,id):
    WaitListEntry.objects.filter(id = id,first_name = first_name, last_name = last_name, RestoID = Restaurant.objects.get(RestoID = RestoID)).delete()
    return redirect('RestoView', RestoID = RestoID)

def SeatEntry(request,RestoID,id):
    RestoWait = Restaurant.objects.get(RestoID = RestoID)
    seatedEntry = WaitListEntry.objects.get(id = id)
    seatedEntry.Seated = True
    seatedEntry.save() #to add time seated to the attributes too
    time_waited = (seatedEntry.TimeOut - seatedEntry.TimeIn).total_seconds()//60
    seatedEntry.WaitTime = time_waited
    seatedEntry.save()
    R9_12Time = WaitListEntry.objects.exclude(WaitTime = None).filter(PaxCount__gte = 9, PaxCount__lte = 12).values_list('WaitTime',flat = True)
    R5_8Time = WaitListEntry.objects.exclude(WaitTime = None).filter(PaxCount__gte = 5, PaxCount__lte = 8).values_list('WaitTime',flat = True)
    R1_4Time = WaitListEntry.objects.exclude(WaitTime = None).filter(PaxCount__gte = 1, PaxCount__lte = 4).values_list('WaitTime',flat = True)
    if seatedEntry.PaxCount >=  9 and seatedEntry.PaxCount <= 12:
        RestoWait.WaitTime9_12 = mode(R9_12Time)
    elif seatedEntry.PaxCount >= 5 and seatedEntry.PaxCount <= 8:
        RestoWait.WaitTime5_8 = mode(R5_8Time)
    elif seatedEntry.PaxCount >= 1 and seatedEntry.PaxCount <=4:
        RestoWait.WaitTime1_4 = mode(R1_4Time)


    # print(R1_4Time)
    #fix the average of the restaurant

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/templates/error.html
<h1>ERROR 404: Page not found</h1>
<p><a href = '#'>Home page</a></p>

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/templates/landingPage.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>ChknGo</title>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	 <!--- Bootstrap Style Sheet --->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Main CSS for the Website -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- Make Category CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/landingPage.css' %}">

	<!--- Work Sans font --->
	<link href="https://fonts.googleapis.com/css?family=Work+Sans&display=swap" rel="stylesheet">

	<!-- For the image -->
	<style type="text/css">
		.jumbotron {
			background-size: cover;
			background-image: url({% static 'imgs/jumbotron-img-bnw.jpg'%});
			background-color: #D8A53E;
		    background-blend-mode: multiply;
		}
	</style>

</head>

<body>
	<div class="jumbotron">
		<div class="container">
			<div class="img">
				<img src="{% static 'imgs/logo.svg' %}" class="img-logo" alt="logo">
			</div>
			<!-- Search bar -->
			<form class="row search-row" action="{% url 'search:searchposts' %}" method="GET" value="{{request.GET.q}}">
				<div class="col-sm">
					<input class="form-control search-bar" type="text" placeholder="Looking for a restaurant?" aria-label="Search" name="q" value="{{request.GET.q}}">
				</div>
				<div class="col-sm">
					<button type="submit" class="btn search-btn" name="submit" value="Search">Search</button>
				</div>
			</form>
		</div>
	</div>

	<div class="container bot-con">
		<h2 class="exp-cat">Explore Categories</h2>
		<!-- Categories divided into 3 per row -->

		{% block categ %}

		{% for category in category_list %}

		{% if forloop.first %}
			<div class="row cat-row">
		{% endif %}

				<a href="#" class="col-sm cat-col shadow"><div><h4>{{ category.CatName }}</h4></div></a>
			
		{% if forloop.counter == 3 %}
			</div>
			<div class="row cat-row">
		{% endif %}

		{% if forloop.last %}
		</div>
		{% endif %}

			
		{% endfor %}

		{% endblock %}

	</div>

	<!-- scripts to make everything smooth -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/templates/login.html
<!DOCTYPE html>
<html>

<head>
	{% load static %}
	<title>ChknGo</title>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!--- Bootstrap Style Sheet --->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<!-- chkngo stylesheet -->
	<link rel="stylesheet" href="{% static 'css/nav.css' %}">
	<!-- login stylesheet -->
	<link rel="stylesheet" href="{% static 'css/login.css' %}">
	<!-- Work Sans Font -->
	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700&display=swap" rel="stylesheet">
</head>

<body>

	<div class="container">
		<div class="d-flex justify-content-center">
			<div class="d-flex login-container rounded">
				<div class="col-sm">
					<div class="row"><h1 class="login-text">Login</h1></div>
					<form method = "POST" class = "form-div">
						{% csrf_token %}
						{{ form.as_p }}
<!-- 						
						<div class="form-group">
							<label for="username">Username:</label>
							<input type="usename" class="form-control" id="email">
						</div>
						<div class="form-group">
							<label for="pwd">Password:</label>
							<input type="password" class="form-control" id="pwd">
						</div>
						<div class="form-group form-check">
							<label class="form-check-label">
								<input class="form-check-input" type="checkbox"> Remember me
							</label>
						</div> -->
						<button type="submit" class="btn btn-success float-right" href = '{% url "LandingPage" %}'>Submit</button>
					</form>
				</div>
			</div>
		</div>
	</div>	

	<!-- scripts to make everything smooth -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	

</body>
</html>

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/templates/logout.html
<!DOCTYPE html>
<html>
<head>
    <title>logout page</title>
</head>
<body>
    <p> You have been logged out! Go to <a href = '{% url "Login" %}' >Login page</a></p>
</body>
</html>

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/templates/make_category.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
    <title>ChknGo</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--- Bootstrap Style Sheet --->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Main CSS for the Website -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- Make Category CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/make_category.css' %}">

    <!-- Work Sans Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700&display=swap" rel="stylesheet">
</head>
<body>
	<div class="container">
		<form class="cat-form" method = "POST" name = 'CategoryForm'>
    	{% csrf_token %}
    	{{ form.as_p }}
    	<button class = "btn upload-btn" type="submit">Upload Category</button>
	</div>
</form>
</body>
</html>

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light">

	<a class="navbar-brand" href="{% url 'LandingPage' %}">ChknGo</a>

	<!-- turns into the smol icon when you go to mobile -->
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<!-- -->

	<!-- allows for collapsability -->
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="">Home<span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item nav-option">
				<a class="nav-link" href="#">View Categories</a>
			</li>
			<li class="nav-item nav-option">
				<form action="{% url 'search:searchposts' %}" method="GET" value="{{request.GET.q}}"> <!-- search bar stuff -->
					<div class="row">
						<div class="col-sm">
							<input class="form-control search-bar" type="text" placeholder="Looking for a restaurant?" aria-label="Search" name="q" value="{{request.GET.q}}">
						</div>
						<div class="col-sm search-btn-col">
							<button type="submit" class="btn search-btn" name="submit" value="Search">Submit</button>
						</div>
					</div>
				</form>
				
			</li>
		</ul>
	</div>
	<!-- -->

</nav>

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/templates/registration_page.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>ChknGo</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--- Bootstrap Style Sheet --->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Main CSS for the Website -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- Registration CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/registration_page.css' %}">

    <!-- Work Sans Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700&display=swap" rel="stylesheet">
</head>
</head>
<body>
    <br>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <form method="POST" class="form-div">
            {% csrf_token %}
            <fieldset class="form-group">
                <h3 class="display-4">Registration</h3>
                <div class="fancy-line"></div>
                <div class="row">
                    <div class="col-sm">
                        {{ form.as_p }}
                    </div>
                    <div class="col-sm" id="hidden_div" style="display: none;">
                        {{ form2.as_p }}
                        <h6>No category? Make one <a href="{% url 'MakeCategory' %}">here!</a><h6>
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn input-btn" type="submit">Sign up</button>
            </div>
            <div>
                <small class="text-muted">Already have an account?<a class="ml-2" href ="{% url 'Login' %}">Log-in here</a></small>
            </div>
        </form>
    </div>
    <br>

    <!-- Source: http://jsfiddle.net/f4PV4/1/ -->
    <script type="text/javascript">
        document.getElementById('id_user_type').addEventListener('change', function () {
            var style = this.value == "RM" ? 'block' : 'none';
            document.getElementById('hidden_div').style.display = style;
        });
    </script>
</body>
</html>

Documents/_My Documents/_School/20192020/1st Sem/CS 123/program/git v4.3.5.2 lets go/chkngo/webapp/templates/search.html
<!DOCTYPE html>
<html>
<h1>Search Page</h1>

<br/>
<body>
	{% csrf_token %}
	<form action="{% url 'search:searchposts' %}" method="GET" value="{{request.GET.q}}">
	Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search a place"/>
	<input type="submit" name="submit" value="Search"/>
	</form>


	{% if submitbutton == 'Search' and request.GET.q != '' %}
		{% if results %}
		<h1>Results for <b>{{ request.GET.q }}</b></h1>
		<br/><br/>

			{% for result in results %}
			<p> <a href = "/restaurants/{{ result.RestoID }}">{{ result.RestoID }}</a> </p>
			<br/>
			{% endfor %}
		{% else %}
		No search results for this query
		{% endif %}
	{% endif %}
</body>
</html>